In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv('https://raw.githubusercontent.com/jackiekazil/data-wrangling/master/data/chp3/data-text.csv')
print(df.head(2))
df1 = pd.read_csv('https://raw.githubusercontent.com/kjam/data-wrangling-pycon/master/data/berlin_weather_oldest.csv')
print(df1.head(2))

                          Indicator PUBLISH STATES  Year WHO region  \
0  Life expectancy at birth (years)      Published  1990     Europe
1  Life expectancy at birth (years)      Published  2000     Europe

  World Bank income group  Country         Sex  Display Value  Numeric  Low  \
0             High-income  Andorra  Both sexes             77     77.0  NaN
1             High-income  Andorra  Both sexes             80     80.0  NaN

   High  Comments
0   NaN       NaN
1   NaN       NaN
             STATION         STATION_NAME      DATE  PRCP  SNWD  SNOW  TMAX  \
0  GHCND:GME00111445  BERLIN TEMPELHOF GM  19310101    46 -9999 -9999 -9999
1  GHCND:GME00111445  BERLIN TEMPELHOF GM  19310102   107 -9999 -9999    50

   TMIN  WDFG  PGTM  ...   WT09  WT07  WT01  WT06  WT05  WT04  WT16  WT08  \
0   -11 -9999 -9999  ...  -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
1    11 -9999 -9999  ...  -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999

   WT18  WT03
0 -9999 -9999
1 -9999 -9999

[2 rows x 21 columns]

In [4]:
df.rename(columns = {'Indicator': 'Indicator_ID'}, inplace = True)
print(df.head(2))

                       Indicator_ID PUBLISH STATES  Year WHO region  \
0  Life expectancy at birth (years)      Published  1990     Europe
1  Life expectancy at birth (years)      Published  2000     Europe

  World Bank income group  Country         Sex  Display Value  Numeric  Low  \
0             High-income  Andorra  Both sexes             77     77.0  NaN
1             High-income  Andorra  Both sexes             80     80.0  NaN

   High  Comments
0   NaN       NaN
1   NaN       NaN

In [6]:
df.sort_values('Year')

,Indicator_ID,PUBLISH STATES,Year,WHO region,World Bank income group,Country,Sex,Display Value,Numeric,Low,High,Comments
0,Life expectancy at birth (years),Published,1990,Europe,High-income,Andorra,Both sexes,77,77.0,NaN,NaN,NaN
1270,Life expectancy at birth (years),Published,1990,Europe,High-income,Germany,Male,72,72.0,NaN,NaN,NaN
3193,Life expectancy at birth (years),Published,1990,Europe,Lower-middle-income,Republic of Moldova,Male,65,65.0,NaN,NaN,NaN
3194,Life expectancy at birth (years),Published,1990,Europe,Lower-middle-income,Republic of Moldova,Both sexes,68,68.0,NaN,NaN,NaN
3197,Life expectancy at age 60 (years),Published,1990,Europe,Lower-middle-income,Republic of Moldova,Male,15,15.0,NaN,NaN,NaN
1264,Life expectancy at birth (years),Published,1990,Europe,High-income,Cyprus,Both sexes,76,76.0,NaN,NaN,NaN
3199,Life expectancy at age 60 (years),Published,1990,Europe,Lower-middle-income,Republic of Moldova,Both sexes,17,17.0,NaN,NaN,NaN
1262,Life expectancy at age 60 (years),Published,1990,Western Pacific,High-income,Cook Islands,Male,17,17.0,NaN,NaN,NaN
1259,Life expectancy at birth (years),Published,1990,Western Pacific,High-income,Cook Islands,Male,67,67.0,NaN,NaN,NaN
3203,Life expectancy at age 60 (years),Published,1990,South-East Asia,Lower-middle-income,Maldives,Female,12,12.0,NaN,NaN,NaN
1273,Life expectancy at age 60 (years),Published,1990,Europe,High-income,Denmark,Both sexes,20,20.0,NaN,NaN,NaN
3204,Life expectancy at birth (years),Published,1990,Western Pacific,Lower-middle-income,Marshall Islands,Female,65,65.0,NaN,NaN,NaN
1253,Life expectancy at birth (years),Published,1990,Western Pacific,High-income,Brunei Darussalam,Both sexes,73,73.0,NaN,NaN,NaN
1247,Life expectancy at age 60 (years),Published,1990,Americas,High-income,Bahamas,Male,17,17.0,NaN,NaN,NaN
3219,Life expectancy at age 60 (years),Published,1990,Western Pacific,Lower-middle-income,Vanuatu,Both sexes,16,16.0,NaN,NaN,NaN
3226,Life expectancy at birth (years),Published,1990,Europe,Upper-middle-income,Bulgaria,Both sexes,71,71.0,NaN,NaN,NaN
1240,Life expectancy at age 60 (years),Published,1990,Europe,High-income,Belgium,Female,23,23.0,NaN,NaN,NaN
1239,Life expectancy at birth (years),Published,1990,Europe,High-income,Belgium,Both sexes,76,76.0,NaN,NaN,NaN
1238,Life expectancy at birth (years),Published,1990,Europe,High-income,Belgium,Female,79,79.0,NaN,NaN,NaN
1237,Life expectancy at birth (years),Published,1990,Europe,High-income,Austria,Both sexes,76,76.0,NaN,NaN,NaN
1236,Life expectancy at birth (years),Published,1990,Europe,High-income,Austria,Male,72,72.0,NaN,NaN,NaN
3207,Life expectancy at birth (years),Published,1990,Western Pacific,Lower-middle-income,Mongolia,Female,64,64.0,NaN,NaN,NaN
3231,Life expectancy at birth (years),Published,1990,Europe,Upper-middle-income,Belarus,Female,76,76.0,NaN,NaN,NaN
3188,Life expectancy at age 60 (years),Published,1990,Africa,Lower-middle-income,Lesotho,Female,17,17.0,NaN,NaN,NaN
1277,Life expectancy at birth (years),Published,1990,Europe,High-income,Estonia,Both sexes,70,70.0,NaN,NaN,NaN
1302,Life expectancy at birth (years),Published,1990,Europe,High-income,Hungary,Male,65,65.0,NaN,NaN,NaN
3158,Life expectancy at birth (years),Published,1990,Europe,Lower-middle-income,Georgia,Male,67,67.0,NaN,NaN,NaN
1300,Life expectancy at birth (years),Published,1990,Europe,High-income,Croatia,Male,69,69.0,NaN,NaN,NaN
3159,Life expectancy at age 60 (years),Published,1990,Europe,Lower-middle-income,Georgia,Both sexes,19,19.0,NaN,NaN,NaN
3160,Life expectancy at age 60 (years),Published,1990,Americas,Lower-middle-income,Guatemala,Female,19,19.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3175,Life expectancy at age 60 (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Iran (Islamic Republic of),Male,19,19.0,NaN,NaN,NaN
3174,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Iran (Islamic Republic of),Female,76,76.0,NaN,NaN,NaN
1285,Life expectancy at birth (years),Published,2012,Europe,High-income,France,Both sexes,82,82.0,NaN,NaN,NaN
1286,Life expectancy at age 60 (years),Published,2012,Europe,High-income,France,Both sexes,25,25.0,NaN,NaN,NaN
3171,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Iran (Islamic Republic of),Male,72,72.0,NaN,NaN,NaN
1288,Life expectancy at age 60 (years),Published,2012,Europe,High-income,United Kingdom of Great Britain and Northern I...,Female,25,25.0,NaN,NaN,NaN
1290,Life expectancy at age 60 (years),Published,2012,Europe,High-income,United Kingdom of Great Britain and Northern I...,Both sexes,24,24.0,NaN,NaN,NaN
1292,Life expectancy at birth (years),Published,2012,Africa,High-income,Equatorial Guinea,Female,57,57.0,NaN,NaN,NaN
3166,Life expectancy at age 60 (years),Published,2012,Americas,Lower-middle-income,Honduras,Male,21,21.0,NaN,NaN,NaN
3165,Life expectancy at birth (years),Published,2012,Americas,Lower-middle-income,Honduras,Both sexes,74,74.0,NaN,NaN,NaN
3163,Life expectancy at age 60 (years),Published,2012,Americas,Lower-middle-income,Guyana,Male,13,13.0,NaN,NaN,NaN
3162,Life expectancy at birth (years),Published,2012,Americas,Lower-middle-income,Guyana,Female,67,67.0,NaN,NaN,NaN
1301,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Croatia,Both sexes,21,21.0,NaN,NaN,NaN
3137,Life expectancy at birth (years),Published,2012,Africa,Lower-middle-income,Cameroon,Male,55,55.0,NaN,NaN,NaN
1303,Life expectancy at birth (years),Published,2012,Europe,High-income,Hungary,Both sexes,75,75.0,NaN,NaN,NaN
3155,Life expectancy at birth (years),Published,2012,Western Pacific,Lower-middle-income,Micronesia (Federated States of),Male,68,68.0,NaN,NaN,NaN
3154,Life expectancy at age 60 (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Egypt,Male,16,16.0,NaN,NaN,NaN
1304,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Hungary,Both sexes,20,20.0,NaN,NaN,NaN
1306,Life expectancy at birth (years),Published,2012,Europe,High-income,Ireland,Female,83,83.0,NaN,NaN,NaN
3150,Life expectancy at age 60 (years),Published,2012,Americas,Lower-middle-income,Ecuador,Male,21,21.0,NaN,NaN,NaN
3148,Life expectancy at birth (years),Published,2012,Americas,Lower-middle-income,Ecuador,Female,78,78.0,NaN,NaN,NaN
3147,Life expectancy at age 60 (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Djibouti,Female,17,17.0,NaN,NaN,NaN
3146,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Djibouti,Both sexes,61,61.0,NaN,NaN,NaN
3145,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,Lower-middle-income,Djibouti,Female,63,63.0,NaN,NaN,NaN
1309,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Ireland,Female,25,25.0,NaN,NaN,NaN
1316,Life expectancy at birth (years),Published,2012,Europe,High-income,Italy,Both sexes,83,83.0,NaN,NaN,NaN
3141,Life expectancy at birth (years),Published,2012,Africa,Lower-middle-income,Cabo Verde,Both sexes,74,74.0,NaN,NaN,NaN
3139,Life expectancy at age 60 (years),Published,2012,Africa,Lower-middle-income,Cameroon,Female,17,17.0,NaN,NaN,NaN
3156,Life expectancy at age 60 (years),Published,2012,Western Pacific,Lower-middle-income,Micronesia (Federated States of),Male,16,16.0,NaN,NaN,NaN
4655,Healthy life expectancy (HALE) at birth (years),Published,2012,Africa,Low-income,Zimbabwe,Female,51,51.0,NaN,NaN,NaN